# Generated by Django 3.2.6 on 2021-08-13 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Function',
            fields=[
                ('FunctionCode', models.AutoField(primary_key=True, serialize=False)),
                ('FunctionName', models.CharField(max_length=50)),
                ('MinSalary', models.IntegerField(null=True)),
                ('MaxSalary', models.IntegerField(null=True)),
                ('DefaultBillingRate', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('PersonID', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=50)),
                ('MiddleName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('Initials', models.CharField(max_length=50)),
                ('Title', models.CharField(max_length=50)),
                ('Gender', models.CharField(max_length=50)),
                ('BirthDate', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('ProjectCode', models.AutoField(primary_key=True, serialize=False)),
                ('ProjectName', models.CharField(max_length=50)),
                ('ProjectDescription', models.CharField(max_length=50)),
                ('ProjectLeader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='task.person')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('TeamCode', models.AutoField(primary_key=True, serialize=False)),
                ('TeamName', models.CharField(max_length=50)),
                ('TeamLeader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='task.person')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('EmployeeID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='task.person')),
                ('TeamCode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='task.team')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('TaskName', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('TaskDescription', models.CharField(max_length=50)),
                ('TaskCost', models.IntegerField()),
                ('TaskDueDate', models.DateField()),
                ('TaskCreateDate', models.DateField()),
                ('ProjectCode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='task.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmployeeID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='task.person')),
                ('ProjectCode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='task.project')),
                ('TeamCode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='task.team')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='TeamCode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='task.team'),
        ),
        migrations.CreateModel(
            name='MemberTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmployeeID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_EmployeeID', to='task.person')),
                ('ProjectCode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_ProjCode', to='task.project')),
                ('TaskName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_TeamName', to='task.team')),
                ('TeamCode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_TeamCode', to='task.team')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('EmployeeBillingRate', models.IntegerField(null=True)),
                ('EmployeeWorkPhone', models.IntegerField(null=True)),
                ('EmployeeFunction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='task.function')),
                ('EmployeeID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='task.person')),
            ],
        ),
    ]
