# Generated by Django 3.2.6 on 2021-08-13 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membertask',
            name='TaskName',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='task.team'),
            preserve_default=False,
        ),
    ]
