# Generated by Django 3.2.6 on 2021-08-13 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_membertask_taskname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membertask',
            name='TaskName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.task'),
        ),
    ]
